FROM node:latest

WORKDIR /app

RUN npm install -g npm@latest
RUN npm install -g pnpm@latest

COPY pnpm-lock.yaml package*.json ./
RUN pnpm install

COPY . .
EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]