services:
  strixcam-web-app-be:
    container_name: strixcam-web-app-be
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../src:/app/src
      - /app/node_modules
    environment:
      - DB_PG_USER=strixcam
      - DB_PG_PASSWORD=strixcam
      - DB_PG_HOST=strixcam-db-postgres
      - DB_PG_PORT=5432
      - DB_PG_DATABASE=strixcam
    networks:
      - strixcam-net-dev

networks:
  strixcam-net-dev:
    external: true
